### ISSUE TITLE
Fill the Data Base with info

### ISSUE THREAD

**Issue by vadym-kobylan** [Stock-FCIT/stock-back#12]

**Comment by Yurko040503** [comment]
Information about flowers was collected from the Internet and added to the database. I will attach the process of adding and the result below:
![Image](https://user-images.githubusercontent.com/72205116/229766797-70391d0b-213e-4460-9517-72c176361e73.png)

![Image](https://user-images.githubusercontent.com/72205116/229767330-c86e2cb0-5229-4694-9c96-e27221bea6b3.png)

![Image](https://user-images.githubusercontent.com/72205116/229767293-3f245058-91ed-4a87-b0ad-f0f8d22104bf.png)

**Comment by vadym-kobylan** [comment]
Good Job!
I'm closing the issue.
